### ISSUE TITLE
silverstripe/versioned 1.13.0 removes deprecated functionality, preventing workflow diff functionality 

### ISSUE THREAD

**Issue by jules0x** [silverstripe-australia/advancedworkflow#488] opened 2023-05-01 23:40 UTC
The latest release of the **silverstripe/silverstripe-versioned** module removes deprecated functionality which breaks the compare functionality of the workflow module.

https://github.com/silverstripe/silverstripe-versioned/compare/1.12.1...1.13.0

Testing:
- I created a blank project: `composer create-project silverstripe/installer test/'
- I added advanced workflow `composer require symbiote/silverstripe-advancedworkflow`
- I then broke the recipes out into their component modules
- Then backed each one down separately until I found the cause

![image](https://user-images.githubusercontent.com/8979741/235549733-47ccc968-d8fd-4f7b-b328-0ca76b4a6904.png)
![image](https://user-images.githubusercontent.com/8979741/235549824-64abe19f-291d-4ffe-8081-449704fc4240.png)

**Comment by GuySartorelli** [comment] 2023-05-03 22:06
Closing, since you have identified the issue as being in silverstripe/versioned and you have created an issue there: https://github.com/silverstripe/silverstripe-versioned/issues/405. Please only create one issue in the future, against only the repository which you think contains the root cause of the problem.

**Closed as not planned by GuySartorelli** 2023-05-03 22:06 UTC

**Comment by toknz** [comment] 2023-06-01 04:32
@GuySartorelli I agree with creating only one issue, but I'm not convinced that raising it against the repository which is or may be the root cause is correct. The issue has been found using this module. Our content advisors raised this issue with our team after we upgraded to CMS 4.13 3 weeks ago. One of our developers started looking at it today and naturally they came to check any issues in this repo. We concur with @jules0x that the same issue exists for us and we will provide more updates soon.

**Comment by Candess** [comment] 2023-06-01 21:45
Hi @jules0x May I know whether the issue fixed? 
Hi @GuySartorelli I'm facing the same problem after CMS upgraded to 4.13. 
The steps to get the error:-
1. User edited the page content and saved
2. Click on Submit for approval
3. Workflow Actions tab displayed with empty data.
![image](https://github.com/symbiote/silverstripe-advancedworkflow/assets/135276483/759bba43-8e75-4535-aa75-4f183e12eca5)

**Comment by GuySartorelli** [comment] 2023-06-08 21:03
The issue representing the root cause was updated 2 days ago to indicate it's in our backlog. Any further discussion will be in that issue.

@toknz The reasons we only want a single issue for each bug are so that all discussion about the bug can be in one place, and so that we don't have to go hunting in ~200 repositories every time we fix a bug to see if it was reported multiple times. I'm going to leave this one closed.
